name: Deploy to GitHub Pages

on:
  push:
    branches: ['main', 'master']

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: 'pages'
  cancel-in-progress: true

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install Project Pieces
        run: npm install

      - name: Compress and Build Site
        run: npm run build

      - name: Setup Pages Routing
        uses: actions/configure-pages@v4

      - name: Gather Final Files
        uses: actions/upload-pages-artifact@v3
        with:
          path: './dist'

      - name: Publish Live to the Internet
        id: deployment
        uses: actions/deploy-pages@v4
